services:
  - type: web
    name: detector-service
    env: docker
    buildCommand: docker build -t detector-service .
    startCommand: gunicorn --bind 0.0.0.0:5000 --workers 4 app:app
    envVars:
      - key: PORT
        value: "5000"
    healthCheckPath: /health
